### ISSUE TITLE
Change wording shares -> cores

### ISSUE THREAD

**Issue by nLight** [dcos/dcos-ui#3335]
The DC/OS dashboard shows overall CPU and GPU allocation but uses the word "shares" when it's actually referring to the total number of "cores". This should just say "cores".

<img width="1595" alt="screen shot 2018-02-05 at 4 30 01 pm" src="https://user-images.githubusercontent.com/186223/46523929-8e662880-c887-11e8-9c24-1175f047fbc5.png">

**Comment by adityatandon007** [comment]
@nLight picking this up

**Comment by nLight** [comment]
\o/ Hey @adityatandon007 if you need any help setting up the project just tell me

**Comment by fanich37** [comment]
How about that 8e12789e054fe2b8057aef7aff64aa519cfb9be9?

**Comment by nLight** [comment]
Hey @fanich37 this one is already taken by @adityatandon007 sorry.
Though I wonder where the commit belong. Github shows it like you committed directly to `dcos/dcos-ui` repo 😅

**Comment by fanich37** [comment]
@nLight lol. I just forked and commited directly to the forked repo. This project is too big to clone it at work )) Will delete it ))

**Comment by adityatandon007** [comment]
@nLight I had successful cloned the repo but what is to be edited in ` webpack/proxy.dev.js` to point to the cluster address. Basically in readme I couldn't understand the part 

> Edit webpack/proxy.dev.js to point to the cluster address

**Comment by nLight** [comment]
@adityatandon007 it is about that part:

https://github.com/dcos/dcos-ui/blob/f54726949fd0c44400ba101cb1d12b317ed1193b/webpack/proxy.template.js#L26
I believe this task doesn't require a cluster at all. 

Just edit your Config.dev.ts 

disable auth plugin setting the respective field to `false`:

https://github.com/dcos/dcos-ui/blob/f54726949fd0c44400ba101cb1d12b317ed1193b/src/js/config/Config.template.ts#L22

and enable fixtures:

https://github.com/dcos/dcos-ui/blob/f54726949fd0c44400ba101cb1d12b317ed1193b/src/js/config/Config.template.ts#L39

https://github.com/dcos/dcos-ui/blob/f54726949fd0c44400ba101cb1d12b317ed1193b/src/js/config/Config.template.ts#L41

**Comment by nLight** [comment]
@adityatandon007 thank you I will pass the message to our design team :) UI is definitely on a heavy side as resources go... We also working on that.

**Comment by nLight** [comment]
It's in! 🎉
