### ISSUE TITLE
Pods: Network name is missing on the review screen

### ISSUE THREAD

**Issue by nLight** [dcos/dcos-ui#3336]
Please refer to the ticket https://jira.mesosphere.com/browse/DCOS_OSS-1370

Needs to be added to: https://github.com/dcos/dcos-ui/blob/master/plugins/services/src/js/service-configuration/PodNetworkConfigSection.js

**Comment by adityatandon007** [comment]
@nLight can I pick this too!

**Comment by nLight** [comment]
@adityatandon007 it's yours :) Thanks!

**Comment by adityatandon007** [comment]
@nLight Does this require the cluster

**Comment by nLight** [comment]
@adityatandon007 I'd say no. You can hit the same screen by trying to launch a multicontainer service:
![oct-05-2018 17-07-52](https://user-images.githubusercontent.com/186223/46543511-52e85000-c8c1-11e8-89bd-edf05575fc77.gif)

**Comment by adityatandon007** [comment]
@nLight I am unable to launch a multi container service

**Comment by nLight** [comment]
@adityatandon007 what is the issue? You don't need to launch it just Proceed until the Review screen

**Comment by adityatandon007** [comment]
@nLight I couldn't launch a multi container service. Here is a screen shot and I figured that I have to add some like this.
`<ConfigurationMapRow>
              <ConfigurationMapLabel>Network Name</ConfigurationMapLabel>
              <ConfigurationMapValueWithDefault
                value={getNetworkTypes(appConfig.networks)}
              />
              {action}
            </ConfigurationMapRow>` but I couldn't start a new multicontainer service. How can I start that.
![screenshot from 2018-10-05 22-13-45](https://user-images.githubusercontent.com/25108385/46548284-40374080-c8ec-11e8-80c5-ffeda730286c.png)

**Comment by adityatandon007** [comment]
@nLight Here is how my services section look. I think there is something wrong with the setup I am not able to see the `+` icon to add a new service.
![screenshot from 2018-10-05 22-20-32](https://user-images.githubusercontent.com/25108385/46548565-16cae480-c8ed-11e8-914e-2f8b6c64f418.png)

**Comment by adityatandon007** [comment]
@nLight any help would be great

**Comment by nLight** [comment]
@adityatandon007 hey, I think those are quirks of running the UI of fixtures. You can't really start anything without a cluster. But clicking into `/some/group-with-pods/podEFGH` should let you see the screen. As I can see from the fixture there is a network with a name.

**Comment by nLight** [comment]
Hey @adityatandon007 is there anything I could do to unblock you?

**Comment by adityatandon007** [comment]
@nLight didn't get what you mean by 

> is there anything I could do to unblock you?
By the way I didn't get the time to look into this. I will try to get to that review screen without starting the cluster. Because I don't know how to set up a cluster.

**Comment by adityatandon007** [comment]
@nLight nope couldn't get to the review screen for a multicontainer pod.

**Comment by adityatandon007** [comment]
@nLight I think I would need to give the cluster url in my config file. But for that I would have to setup an aws cluster. I don't want to go throught that setup. Is there any dummy cluster url that I can add to config file to start the cluster. If there is no other way to set up a cluster url then, some else is free to pick this up!

**Comment by nLight** [comment]
@adityatandon007 you don't need a cluster for that. Just click into this `/some/group-with-pods/podEFGH` then `Configuration` tab - that's the same screen

**Comment by adityatandon007** [comment]
@nLight I got that but I want to ask that I am not able to see the network type and I know because the `appConfig.networks ` might be null but then how can I get the name of the network. 

![screenshot from 2018-10-09 21-00-00](https://user-images.githubusercontent.com/25108385/46680471-d1692880-cc06-11e8-8dbe-3bfa23e27d5c.png)

**Comment by adityatandon007** [comment]
@nLight I have added the `Network Name`  under `Networking` but it still needs to call the function to get the name of the network like it is doing in case of `Network Type` but I can't get to output since I don't know what `key` it is to used to get the network name since my `appConfig.networks` is null. I know I'm almost there.
![screenshot from 2018-10-09 21-08-10](https://user-images.githubusercontent.com/25108385/46681061-0fb31780-cc08-11e8-96f7-996548bde1cf.png)

**Comment by nLight** [comment]
Let me see...

**Comment by nLight** [comment]
Could you please create a work in progress PR?

**Comment by nLight** [comment]
It's in! Thank you for the effort! 🍁
