### ISSUE TITLE
Owner column alignment is incorrect on the files tab of a task detail

### ISSUE THREAD

**Issue by nLight** [dcos/dcos-ui#3337]
Please refer to the issue https://jira.mesosphere.com/browse/DCOS_OSS-4245

File to look: https://github.com/dcos/dcos-ui/blob/f54726949fd0c44400ba101cb1d12b317ed1193b/plugins/services/src/js/components/TaskDirectoryTable.js#L169

**Comment by sharynneazhar** [comment]
I'll take a stab at this 🙂

**Comment by nLight** [comment]
@sharynneazhar awesome, thank you! Please glance over our commit guidelines: https://github.com/dcos/dcos-ui/blob/master/CONTRIBUTING.md#commit-message it should be something like:
```
fix: left align owner col

Closes DCOS_OSS-4245
```

🙇

**Comment by nLight** [comment]
How's it going @sharynneazhar? Can I help you with anything?

**Comment by sharynneazhar** [comment]
Sorry. I was planning on getting this done this weekend. Work got really busy in the last couple of weeks. Deployment pains. 😅

**Comment by sharynneazhar** [comment]
@nLight, I have the changes needed for this issue but I'm actually having issues running the app locally and through docker. 

Locally, the steps in `proxy.dev.js` seems a little outdated. E.g. `src/webui/master` does not exist in the repo. I tried starting the server on `src/webui` but no luck. 

Through docker, I'm running into this issue which I'm guessing is an auth issue. 

```
ERROR: Service 'toolchain' failed to build: pull access denied for mesosphere/dcos-system-test-driver
````

**Comment by nLight** [comment]
Hi @sharynneazhar. I'm sorry, unfortunately the `Dockerfile` is based off a private image. You could launching the UI locally by following this instructions https://github.com/dcos/dcos-ui/issues/3340#issuecomment-431275763 or I believe changing the base image in the `Dockerfile` to `python:3` should work too. Or you could also create a WIP PR for us to test.

Thank you for the effort!

**Comment by nLight** [comment]
\o/ it's in! Thanks once again!
