### ISSUE TITLE
Location breadcrumb should start with uppercase "S"

### ISSUE THREAD

**Issue by nLight** [dcos/dcos-ui#3338]
In the deployment Modal

![bildschirmfoto 2018-09-17 um 12 46 19](https://user-images.githubusercontent.com/186223/46528669-a8f2ce80-c894-11e8-934a-c2c1702a4f58.png)

https://github.com/dcos/dcos-ui/blob/master/plugins/services/src/js/components/DeploymentsModal.js#L232

**Comment by shubhamcr** [comment]
Can I fix this ?

**Comment by nLight** [comment]
Hey @shubhamcr, sure! Please do 🙇

**Comment by nLight** [comment]
https://github.com/dcos/dcos-ui/pull/3339

**Comment by nLight** [comment]
@shubhamcr thank you for the contribution it's in! 🍁 🎉
