### ISSUE TITLE
Catalog package number configuration does not accept floating point

### ISSUE THREAD

**Issue by nLight** [dcos/dcos-ui#3340]
Please refer to the ticket https://jira.mesosphere.com/browse/DCOS_OSS-2065

Possible solution https://jira.mesosphere.com/browse/DCOS_OSS-2065?focusedCommentId=176587&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-176587

**Comment by nLight** [comment]
@Viscontes please go ahead 🙇

**Comment by Viscontes** [comment]
@nLight I am sorry but I cannot install project locally. How could I get some help?

**Comment by nLight** [comment]
@Viscontes sure, no worries! What stage you are at?

**Comment by Viscontes** [comment]
@nLight I installed mesos project and dcos-ui project. However, in dcos-ui/src/webui I did not have master folder. I tried to launch server in webui folder but on localhost:8000/mesos I got 404: File not found. I don't know what to do. Maybe you have some ideas how to fix this?

**Comment by nLight** [comment]
Hi @Viscontes! You should not need anything except the UI. If you follow the install instructions https://github.com/dcos/dcos-ui#local-development and replace src/js/config/Config.dev.ts with:

```js
// Configuration overrides

export default {
  analyticsKey: "39uhSEOoRHMw6cMR6st9tYXDbAL3JSaP",
  rootUrl: "",
  historyServer: "",
  // Override cluster's uiConfiguration for development
  uiConfigurationFixture: {
    uiConfiguration: {
      plugins: {
        banner: {
          enabled: false
        },
        intercom: {
          enabled: false,
          appId: "wn4z9z0y"
        },
        mesos: {
          "logging-strategy": "logrotate"
        },
        oauth: {
          enabled: false,
          authHost: "https://dcos.auth0.com"
        },
        "overview-detail": {
          enabled: true
        },
        tracking: {
          enabled: false
        }
      }
    },
    clusterConfiguration: {
      firstUser: true,
      id: "ui-fixture-cluster-id"
    }
  },
  // Use fixtures to mock API requests
  useFixtures: true,
  // Use uiConfigurationFixture defined above
  useUIConfigFixtures: true
};
```

 after `npm start` the UI should be available at `http://localhost:4200`

**Comment by Viscontes** [comment]
@nLight Thank you a lot. Is it okay that I have 504 errors and Uncaught TypeError: Cannot read property 'success' of null ?

**Comment by nLight** [comment]
@Viscontes our fixtures aren't 100% solid, does it block you from getting to the form? 

I tried illustrating the bug:

![oct-19-2018 18-31-59](https://user-images.githubusercontent.com/186223/47231509-5d304100-d3cd-11e8-9f1b-fd600ff543d3.gif)

With fixtures it's not going to be Cassandra, but the important point is to fix decimal fields.

Thanks!

**Comment by Viscontes** [comment]
@nLight for me it looks like this. 
![selection_010](https://user-images.githubusercontent.com/11841201/47288293-3147d200-d5fe-11e8-9950-daf1d3d1439a.png)
I have this picture on every package. I just cannot open that form. Could you please suggest me something?

**Comment by nLight** [comment]
Hi @Viscontes, just hit `Review and run` to get to the form. It will look different, because it's a different package, but then the bug should be reproducible on any `<input type="number" />` field.

**Comment by nLight** [comment]
It's been resolved. Thanks everyone! #3451
